// UKSFTA Mission Init
// Generated by Platinum DevOps Suite

if (isServer) then {
    // Server-side logic (Global variables, DB init, etc.)
};

if (hasInterface) then {
    // Client-side logic (UI, Briefing, HUD)
};
