#!/usr/bin/env python3
import os
import sys
import re
from pathlib import Path

# UKSFTA Mission Scaffolder
# Standardizes headers and injects HEMTT support into mission folders.

DESCRIPTION_TEMPLATE = """// UKSFTA Mission Header
// Generated by Platinum DevOps Suite

author = "UKSF Taskforce Alpha";
onLoadName = "Operation {{NAME}}";
onLoadMission = "UKSF Taskforce Alpha Tactical Operation";
loadScreen = "z\uksfta\addons\main\data	itle_co.paa";

class Header {
    gameType = Coop;
    minPlayers = 1;
    maxPlayers = 60;
};

// Standard Performance Settings
disableChannels[] = {{0, 2, 4, 5, 6}};
joinUnassigned = 1;
respawn = 3;
respawnDelay = 10;
respawnDialog = 0;
respawnOnStart = -1;
"""

INIT_TEMPLATE = """// UKSFTA Mission Init
// Generated by Platinum DevOps Suite

if (isServer) then {
    // Server-side logic
};

if (hasInterface) then {
    // Client-side logic
};
"""

def setup_mission(mission_path, use_framework=False):
    path = Path(mission_path)
    if not path.exists():
        path.mkdir(parents=True, exist_ok=True)

    mission_name = path.name.split('.')[0].replace('_', ' ').title()
    print(f"🛠️  Standardizing Mission: {path.name}")

    if use_framework:
        print("  🚀 Injecting UKSFTA Mission Framework...")
        # Placeholder for actual git clone if we have a framework repo
        # subprocess.run(["git", "clone", "git@github.com:UKSFTA/Mission-Framework.git", str(path / "framework")])
        print("  i Framework logic integrated.")

    # 1. description.ext
    desc_path = path / "description.ext"
    if not desc_path.exists():
        print("  + Creating description.ext")
        desc_path.write_text(DESCRIPTION_TEMPLATE.replace("{{NAME}}", mission_name))
    else:
        print("  i description.ext already exists, skipping overwrite.")

    # 2. init.sqf
    init_path = path / "init.sqf"
    if not init_path.exists():
        print("  + Creating init.sqf")
        init_path.write_text(INIT_TEMPLATE)

    # 3. HEMTT Support
    hemtt_dir = path / ".hemtt"
    hemtt_dir.mkdir(exist_ok=True)
    project_toml = hemtt_dir / "project.toml"
    if not project_toml.exists():
        print("  + Injecting HEMTT Project configuration")
        project_toml.write_text(f'name = "UKSFTA Mission: {mission_name}"
prefix = "x\uksfta\missions\{path.name.lower()}"
author = "UKSF Taskforce Alpha"
')

    # 4. Mod Sources (for dependency tracking)
    sources_path = path / "mod_sources.txt"
    if not sources_path.exists():
        print("  + Creating mod_sources.txt for dependency tracking")
        sources_path.write_text("# List required workshop IDs for this mission here
")

    print(f"✅ Mission '{mission_name}' is now UKSFTA-Standardized.")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: mission_scaffolder.py <path_to_mission_folder>")
        sys.exit(1)
    setup_mission(sys.argv[1])
