#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import os
import sys
import subprocess
import json
import argparse
from datetime import datetime
from pathlib import Path

# UKSFTA Unit Health Report Generator
# Consumes data from workspace_manager audit and dashboard to create a production status page.

def generate_report(root_dir, dry_run=False):
    root = Path(root_dir)
    report_path = root / "UNIT_HEALTH_REPORT.md"
    
    # 1. Gather Data via manager (JSON mode)
    # We call these internally to populate the report
    dash_res = subprocess.run([sys.executable, str(root / "tools" / "workspace_manager.py"), "--json", "dashboard"], capture_output=True, text=True)
    dash_data = json.loads(dash_res.stdout) if dash_res.returncode == 0 else []

    ws_res = subprocess.run([sys.executable, str(root / "tools" / "workspace_manager.py"), "--json", "audit-updates"], capture_output=True, text=True)
    ws_data = json.loads(ws_res.stdout) if ws_res.returncode == 0 else []

    md_lines = []
    md_lines.append(f"# 🛡️ UKSFTA Unit Health Report")
    md_lines.append(f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
    
    md_lines.append("## 📦 Project Overview")
    md_lines.append("| Project | Version | Components | Status |")
    md_lines.append("| :--- | :--- | :--- | :--- |")
    for p in dash_data:
        pbos = len(p['pbos'])
        status = "✅ OK" if p['sync_state'] == "OK" else "⚠️ PENDING"
        md_lines.append(f"| {p['project']} | {p['version']} | {pbos} PBOs | {status} |")
    
    md_lines.append("\n## 🌐 Workshop Synchronization")
    md_lines.append("| Mod Name | Project | Locked | Live | Status |")
    md_lines.append("| :--- | :--- | :--- | :--- | :--- |")
    updates_needed = 0
    for m in ws_data:
        status = "✅ Current" if m['up_to_date'] else "❌ Update Available"
        if not m['up_to_date']: updates_needed += 1
        md_lines.append(f"| {m['name']} | {m['project']} | `{m['locked']}` | `{m['live']}` | {status} |")

    md_lines.append("\n## 🛠️ Required Actions")
    if updates_needed > 0:
        md_lines.append(f"- [ ] **Workshop**: {updates_needed} mods are out of date. Run `./tools/workspace_manager.py apply-updates`.")
    
    for p in dash_data:
        if p['sync_state'] != "OK":
            md_lines.append(f"- [ ] **Project**: {p['project']} requires a local mod sync. Run `./tools/workspace_manager.py sync` inside the project.")
    
    if updates_needed == 0 and all(p['sync_state'] == "OK" for p in dash_data):
        md_lines.append("- ✅ All systems nominal. No immediate actions required.")

    md_lines.append("\n---\n*Generated by UKSFTA Platinum DevOps Suite*")
    
    full_report = "\n".join(md_lines)
    
    if dry_run:
        print("\n--- 🕵️ REPORT DRY-RUN PREVIEW ---")
        print(full_report)
        print("-------------------------------\n")
    else:
        with open(report_path, "w") as f:
            f.write(full_report)
        print(f"✅ Report saved to: {report_path}")

def main():
    parser = argparse.ArgumentParser(description="UKSFTA Health Report Generator")
    parser.add_argument("--dry-run", action="store_true", help="Preview report in console")
    args = parser.parse_args()
    
    root_dir = Path(__file__).parent.parent
    generate_report(root_dir, args.dry_run)

if __name__ == "__main__":
    main()
