#!/usr/bin/env python3
import os
import sys
import json
import subprocess
from datetime import datetime
from pathlib import Path

# UKSFTA Unit Health Report Generator
# Consolidates all audit data into a single Markdown report.

def generate_report(root_dir):
    root = Path(root_dir)
    report_path = root / "UNIT_HEALTH_REPORT.md"
    
    print("📊 Generating Global Unit Health Report...")
    
    # 1. Fetch Dashboard Data (JSON)
    manager = root / "tools" / "workspace_manager.py"
    dash_res = subprocess.run([sys.executable, str(manager), "--json", "dashboard"], capture_output=True, text=True)
    dash_data = json.loads(dash_res.stdout) if dash_res.returncode == 0 else []

    # 2. Fetch Workshop Data (JSON)
    ws_res = subprocess.run([sys.executable, str(manager), "--json", "audit-updates"], capture_output=True, text=True)
    ws_data = json.loads(ws_res.stdout) if ws_res.returncode == 0 else []

    with open(report_path, "w") as f:
        f.write(f"# 🛡️ UKSFTA Unit Health Report
")
        f.write(f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

")
        
        f.write("## 📦 Project Overview
")
        f.write("| Project | Version | Components | Status |
")
        f.write("| :--- | :--- | :--- | :--- |
")
        for p in dash_data:
            pbos = len(p['pbos'])
            status = "✅ OK" if p['sync_state'] == "OK" else "⚠️ PENDING"
            f.write(f"| {p['project']} | {p['version']} | {pbos} PBOs | {status} |
")
        
        f.write("
## 🌐 Workshop Synchronization
")
        f.write("| Mod Name | Project | Locked | Live | Status |
")
        f.write("| :--- | :--- | :--- | :--- | :--- |
")
        updates_needed = 0
        for m in ws_data:
            status = "✅ Current" if m['up_to_date'] else "❌ Update Available"
            if not m['up_to_date']: updates_needed += 1
            f.write(f"| {m['name']} | {m['project']} | `{m['locked']}` | `{m['live']}` | {status} |
")

        f.write("
## 🛠️ Required Actions
")
        if updates_needed > 0:
            f.write(f"- [ ] **Workshop**: {updates_needed} mods are out of date. Run `./tools/workspace_manager.py apply-updates`.
")
        
        for p in dash_data:
            if p['sync_state'] != "OK":
                f.write(f"- [ ] **Project**: {p['project']} requires a local mod sync. Run `./tools/workspace_manager.py sync` inside the project.
")
        
        if updates_needed == 0 and all(p['sync_state'] == "OK" for p in dash_data):
            f.write("- ✅ All systems nominal. No immediate actions required.
")

        f.write("
---
*Generated by UKSFTA Platinum DevOps Suite*")

    print(f"✅ Report saved to: {report_path}")

if __name__ == "__main__":
    generate_report(Path(__file__).parent.parent)
